export const data:any = [
  {
    id: 1,
    img: "http://via.placeholder.com/640x360",
    title: "Alert",
    description: "Alert informs users about important Events",
  },
  {
    id: 2,
    img: "http://via.placeholder.com/640x360",
    title: "Input",
    description: "Alert informs users about important Events",
  },
  {
    id: 3,
    img: "http://via.placeholder.com/640x360",
    title: "Card",
    description: "Alert informs users about important Events",
  },
  {
    id: 4,
    img: "http://via.placeholder.com/640x360",
    title: "title1",
    description: "Alert informs users about important Events",
  },
  {
    id: 5,
    img: "http://via.placeholder.com/640x360",
    title: "Navigation",
    description: "Alert informs users about important Events",
  },
  {
    id: 6,
    img: "http://via.placeholder.com/640x360",
    title: "Couresel",
    description: "Alert informs users about important Events",
  },
  {
    id: 7,
    img: "http://via.placeholder.com/640x360",
    title: "Collapse",
    description: "Alert informs users about important Events",
  },
  {
    id: 8,
    img: "http://via.placeholder.com/640x360",
    title: "Button",
    description: "Alert informs users about important Events",
  },
  {
    id: 9,
    img: "http://via.placeholder.com/640x360",
    title: "Text Area",
    description: "Alert informs users about important Events",
  },
  {
    id: 10,
    img: "http://via.placeholder.com/640x360",
    title: "Input",
    description: "Alert informs users about important Events",
  },
  {
    id: 11,
    img: "http://via.placeholder.com/640x360",
    title: "Navbar",
    description: "Alert informs users about important Events",
  },
  {
    id: 12,
    img: "http://via.placeholder.com/640x360",
    title: "BreadCrumb",
    description: "Alert informs users about important Events",
  },
  {
    id: 13,
    img: "http://via.placeholder.com/640x360",
    title: "Input",
    description: "Alert informs users about important Events",
  },
];
